#!/bin/sh

set -eu

allowed_signers=${1:-"$HOME/.config/git/allowed_signers"}

[ -r "$allowed_signers" ] || exit 1

agent_keys=$(ssh-add -L 2>/dev/null || true)
[ -n "$agent_keys" ] || exit 1

printf '%s\n' "$agent_keys" | awk '
  BEGIN {
    found = 0
  }

  NR == FNR {
    if ($1 ~ /^(ssh-|ecdsa-|sk-)/ && $0 !~ /-cert-/) {
      agent[$1 " " $2] = 1
    }
    next
  }

  /^[[:space:]]*(#|$)/ {
    next
  }

  {
    for (i = 1; i <= NF; i++) {
      if ($i ~ /^(ssh-|ecdsa-|sk-)/ && (i + 1) <= NF) {
        key = $i " " $(i + 1)
        if (key in agent) {
          out = $i " " $(i + 1)
          for (j = i + 2; j <= NF; j++) {
            out = out " " $j
          }
          print "key::" out
          found = 1
          exit 0
        }
        break
      }
    }
  }

  END {
    if (found) {
      exit 0
    }
    exit 1
  }
' - "$allowed_signers"