contexts:
  default:
    options:
      DOTFILES_SCRIPT:
        value: install.sh
      DOTFILES_URL:
        value: https://github.com/szkiba/dotfiles.git
    defaultIde: vscode
    defaultProvider: docker
    providers:
      docker:
        creationTimestamp: null
        initialized: true
        options:
          DOCKER_BUILDER: {}
          DOCKER_HOST: {}
          DOCKER_PATH:
            value: docker
          INACTIVITY_TIMEOUT: {}
